window.DEMO_CLASES = [
  {
    "codigo": "1A",
    "titulo": "Potras 1 Año|1A",
    "orden": 1,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 1,
        "dorsal": 1,
        "nombre": "DONNA H.V.",
        "fecha_nacimiento": "2025-08-16",
        "capa": "TORDA",
        "padre": "MAGIC MAGNIFIQUE",
        "madre": "AFRODITA E.A.",
        "abuelo_materno": "EXCALIBUR E.A.",
        "criador": "VACOR ARABIANS",
        "propietario": "VACOR ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 2,
        "dorsal": 2,
        "nombre": "ALIRA DE CARO",
        "fecha_nacimiento": "2025-06-05",
        "capa": "ALAZANA",
        "padre": "IE OTHAR",
        "madre": "TRIANA DE LUC",
        "abuelo_materno": "COLISEUM E.A.",
        "criador": "CARO ARABIANS",
        "propietario": "CARO ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 3,
        "dorsal": 3,
        "nombre": "MZ SHAMS",
        "fecha_nacimiento": "2025-05-22",
        "capa": "TORDA",
        "padre": "ZEUS EA",
        "madre": "STARBOARD BOW",
        "abuelo_materno": "STIVAL (US)",
        "criador": "MARTA ZEA",
        "propietario": "ZEA ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "1B",
    "titulo": "Potras 1 Año|1B",
    "orden": 2,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 4,
        "dorsal": 4,
        "nombre": "LAA DAMARIS",
        "fecha_nacimiento": "2025-03-18",
        "capa": "TORDA",
        "padre": "LR SOLO MIO",
        "madre": "VENECIA DE LUC",
        "abuelo_materno": "SHANGHAI E.A.",
        "criador": "MAYRIT ARABIANS STUD",
        "propietario": "MAYRIT ARABIANS STUD",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 5,
        "dorsal": 5,
        "nombre": "BELA DE LABA",
        "fecha_nacimiento": "2025-03-10",
        "capa": "CASTAÑA",
        "padre": "W.F. GAWIN",
        "madre": "BERNARDINA DE LABA",
        "abuelo_materno": "EXCALIBUR E.A.",
        "criador": "YEGUADA LABA",
        "propietario": "YEGUADA LABA",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 6,
        "dorsal": 6,
        "nombre": "SG TRENZA",
        "fecha_nacimiento": "2025-03-08",
        "capa": "ALAZANA",
        "padre": "ABHA RIYADH",
        "madre": "YASMIN AL ZARAQ",
        "abuelo_materno": "L.C. HAREM",
        "criador": "YEGUADA SIERRA GORDA",
        "propietario": "YEGUADA SIERRA GORDA",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 7,
        "dorsal": 7,
        "nombre": "SG TRIPOLI",
        "fecha_nacimiento": "2025-02-26",
        "capa": "CASTAÑA",
        "padre": "ABHA RIYADH",
        "madre": "SG LIBIA",
        "abuelo_materno": "COLISEUM E.A.",
        "criador": "YEGUADA SIERRA GORDA",
        "propietario": "YEGUADA SIERRA GORDA",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "2A",
    "titulo": "Potros 1 Año|2A",
    "orden": 3,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 8,
        "dorsal": 8,
        "nombre": "AZHIR SAHIB NE",
        "fecha_nacimiento": "2025-08-20",
        "capa": "ALAZAN",
        "padre": "AJ SANADA",
        "madre": "KALAIAH AL ZUBI",
        "abuelo_materno": "EB JAMAL",
        "criador": "GARALOCES ARABIANS",
        "propietario": "GARALOCES ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 9,
        "dorsal": 9,
        "nombre": "OBIXENTH AL ZUBI",
        "fecha_nacimiento": "2025-06-05",
        "capa": "CASTAÑO",
        "padre": "EXAGON OS",
        "madre": "JULIETTAH AL ZUBI",
        "abuelo_materno": "KANZ ALBIDAYER",
        "criador": "ZUBIALDEA ARABIANS",
        "propietario": "ZUBIALDEA ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 10,
        "dorsal": 10,
        "nombre": "SOÑADOR A.A.",
        "fecha_nacimiento": "2025-05-15",
        "capa": "TORDO",
        "padre": "DLM KEOPS",
        "madre": "REINA A.A.",
        "abuelo_materno": "ADAGIO DE LUC",
        "criador": "YEGUADA ARCOS ARABIANS",
        "propietario": "YEGUADA ARCOS ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "2B",
    "titulo": "Potros 1 Año|2B",
    "orden": 4,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 11,
        "dorsal": 11,
        "nombre": "MZ SHAMAL",
        "fecha_nacimiento": "2025-05-07",
        "capa": "TORDO",
        "padre": "SAHM EL ARAB",
        "madre": "LÍBIA DE LUC",
        "abuelo_materno": "FLAVIO DE LUC",
        "criador": "MARTA ZEA",
        "propietario": "ZEA ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 12,
        "dorsal": 12,
        "nombre": "SHIO ISAL",
        "fecha_nacimiento": "2025-04-20",
        "capa": "CASTAÑO",
        "padre": "SA FALCO",
        "madre": "DAA ISOLDA",
        "abuelo_materno": "QR MARC",
        "criador": "SHIDOME GROUP",
        "propietario": "LOS GEMELOS",
        "notas": "El propietario no coinciden en AECCA",
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 13,
        "dorsal": 13,
        "nombre": "SUNDAR AA",
        "fecha_nacimiento": "2025-03-21",
        "capa": "CASTAÑO",
        "padre": "AJ MARZAN",
        "madre": "SARAI AA",
        "abuelo_materno": "JYAR MEIA LUA",
        "criador": "ARIELA ARABIANS FARM",
        "propietario": "LA ESPARTERA",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 14,
        "dorsal": 14,
        "nombre": "NUNO R.C.",
        "fecha_nacimiento": "2025-03-18",
        "capa": "ALAZAN",
        "padre": "FM THOR",
        "madre": "MODICA DE LAGUNILLAS",
        "abuelo_materno": "ABHA VOLTAIRE",
        "criador": "ARABIANS RODRÍGUEZ CASADO",
        "propietario": "ARABIANS RODRÍGUEZ CASADO",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "3",
    "titulo": "Potras|2 Años",
    "orden": 5,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 15,
        "dorsal": 15,
        "nombre": "L.G. UNIKA",
        "fecha_nacimiento": "2024-07-08",
        "capa": "TORDA",
        "padre": "BV UNIK",
        "madre": "ANUSCHKA",
        "abuelo_materno": "CLASSIC KARIM",
        "criador": "LOS GEMELOS",
        "propietario": "YEGUADA MI SUEÑO",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 16,
        "dorsal": 16,
        "nombre": "LAA CASSANDRA",
        "fecha_nacimiento": "2024-05-09",
        "capa": "TORDA",
        "padre": "WF GAWIN",
        "madre": "DAA ATHENA",
        "abuelo_materno": "MAKISA ADAGGIO",
        "criador": "MAYRIT ARABIANS STUD",
        "propietario": "MAYRIT ARABIANS STUD",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 17,
        "dorsal": 17,
        "nombre": "MZ ANNA ALISHEEBA",
        "fecha_nacimiento": "2024-04-27",
        "capa": "TORDA",
        "padre": "ATILA DE LUC",
        "madre": "SG NIEBLA",
        "abuelo_materno": "ABHA ORIX",
        "criador": "ZEA ARABIANS",
        "propietario": "EVA CABRERA - GANADERÍA NOBLEZA ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 18,
        "dorsal": 18,
        "nombre": "JAMAL YAMIRA",
        "fecha_nacimiento": "2024-03-23",
        "capa": "ALAZANA",
        "padre": "ESTORIL EA",
        "madre": "ABHA ODALIC",
        "abuelo_materno": "KHIDAR",
        "criador": "JAMAL ARABIANS",
        "propietario": "JUAL ELIAS RODRIGUEZ - EL RUBIAL",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 19,
        "dorsal": 19,
        "nombre": "SHIO JAVA",
        "fecha_nacimiento": "2024-03-21",
        "capa": "ALAZANA",
        "padre": "AJ SANAD",
        "madre": "JADA",
        "abuelo_materno": "QR MARC",
        "criador": "SHIODOME GROUP",
        "propietario": "LOS GEMELOS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "4",
    "titulo": "Potras|3 Años",
    "orden": 6,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 20,
        "dorsal": 20,
        "nombre": "MAGIC DE MI SUEÑO",
        "fecha_nacimiento": "2023-10-20",
        "capa": "TORDA",
        "padre": "ABHA CALIFA",
        "madre": "ULMARIA B",
        "abuelo_materno": "QUIMONANT",
        "criador": "YEGUADA MI SUEÑO",
        "propietario": "YEGUADA MI SUEÑO",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 21,
        "dorsal": 21,
        "nombre": "SHIO JULIA",
        "fecha_nacimiento": "2023-07-17",
        "capa": "ALAZANA",
        "padre": "DOMINIC M",
        "madre": "JADA",
        "abuelo_materno": "QR MARC",
        "criador": "SHIODOME GROUP",
        "propietario": "ADRIAN RODRIGUEZ MORAN",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 22,
        "dorsal": 22,
        "nombre": "LEENA AL SHIRAA",
        "fecha_nacimiento": "2023-06-13",
        "capa": "ALAZANA",
        "padre": "LAUREL EL JYAR",
        "madre": "GHAYAT ALSBA",
        "abuelo_materno": "SHAEL DREAM DESERT",
        "criador": "AL SHIRAA ARABIANS",
        "propietario": "YEGUADA NORA",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 23,
        "dorsal": 23,
        "nombre": "AMS AL ZAHRA",
        "fecha_nacimiento": "2023-06-07",
        "capa": "ALAZANA",
        "padre": "HERODOTUS AL SHIRAA",
        "madre": "AMS ARALIA",
        "abuelo_materno": "SHAMIL AL CAPÉ",
        "criador": "AMOROS ARABIAN",
        "propietario": "AMOROS ARABIAN",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 24,
        "dorsal": 24,
        "nombre": "LUANA AL SHIRAA",
        "fecha_nacimiento": "2023-04-29",
        "capa": "ALAZANA",
        "padre": "HERODOTUS AL SHIRAA",
        "madre": "D JAMAYEL",
        "abuelo_materno": "FA EL RASHEEM",
        "criador": "AL SHIRAA ARABIANS",
        "propietario": "IAGO y BORJA",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "5",
    "titulo": "Potros|2 Años",
    "orden": 7,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 25,
        "dorsal": 25,
        "nombre": "EROS PB",
        "fecha_nacimiento": "2024-06-20",
        "capa": "TORDO",
        "padre": "HARBI AL ADWAN",
        "madre": "ELISHARA",
        "abuelo_materno": "KHIDAR",
        "criador": "DAVID PUJALT & TINA BAUMGARTNER",
        "propietario": "NIRRI ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 26,
        "dorsal": 26,
        "nombre": "SG SAMOS",
        "fecha_nacimiento": "2024-04-11",
        "capa": "ALAZAN",
        "padre": "AJ SANAD",
        "madre": "SG MYLLAS",
        "abuelo_materno": "FLAVIO DE LUC",
        "criador": "YEGUADA SIERRA GORDA",
        "propietario": "YEGUADA SIERRA GORDA",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 27,
        "dorsal": 27,
        "nombre": "LAA CYRO",
        "fecha_nacimiento": "2024-03-24",
        "capa": "TORDO",
        "padre": "MEDAN AL SHAQAB",
        "madre": "DAA BAMBOLINA",
        "abuelo_materno": "AJMAN MONISCIONE",
        "criador": "MAYRIT ARABIANS STUD",
        "propietario": "MAYRIT ARABIANS STUD",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 28,
        "dorsal": 28,
        "nombre": "VOLCAN DE TAGORO*",
        "fecha_nacimiento": "2024-03-24",
        "capa": "ALAZAN",
        "padre": "ORGAZ ES",
        "madre": "NYORA",
        "abuelo_materno": "IZABAL",
        "criador": "VOLCAN STUD",
        "propietario": "VOLCAN STUD",
        "notas": "Pure Spanish",
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "6",
    "titulo": "Potros|3 Años",
    "orden": 8,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 29,
        "dorsal": 29,
        "nombre": "JAMAL XANDROS",
        "fecha_nacimiento": "2023-09-26",
        "capa": "TORDO",
        "padre": "ESTORIL EA",
        "madre": "DAPHNE K",
        "abuelo_materno": "WH JUSTICE",
        "criador": "JAMAL ARABIANS",
        "propietario": "ROCIO MORENO - MORENO ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 30,
        "dorsal": 30,
        "nombre": "JOAN",
        "fecha_nacimiento": "2023-05-06",
        "capa": "TORDO",
        "padre": "HARIRY AL SHAQAB",
        "madre": "JAYWAN AL BIDAYER",
        "abuelo_materno": "D KHATTAF",
        "criador": "AL BAYDAA FARM",
        "propietario": "YEGUADA NORA",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "7",
    "titulo": "Yeguas|4 - 6 Años",
    "orden": 9,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 31,
        "dorsal": 31,
        "nombre": "AMEIXENDA DE LUC",
        "fecha_nacimiento": "2021-06-28",
        "capa": "TORDA",
        "padre": "COLISEUM E.A.",
        "madre": "ABHA NINUFAR",
        "abuelo_materno": "MARWAN AL SHAQAB (QA)",
        "criador": "VEL JACIR S.C.",
        "propietario": "ARABIANS RODRÍGUEZ CASADO",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 32,
        "dorsal": 32,
        "nombre": "VOLCAN DE ISORA*",
        "fecha_nacimiento": "2021-05-31",
        "capa": "TORDA",
        "padre": "ROHF OMAN",
        "madre": "NYORA",
        "abuelo_materno": "IZABAL",
        "criador": "VOLCAN STUD",
        "propietario": "VOLCAN STUD",
        "notas": "Pure Spanish",
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 33,
        "dorsal": 33,
        "nombre": "AL-QAHIRA GA",
        "fecha_nacimiento": "2020-05-18",
        "capa": "CASTAÑA",
        "padre": "EXCALIBUR EA",
        "madre": "  ABHA UDAIPUR",
        "abuelo_materno": "ABHA PESHAWAR",
        "criador": "ANTONIO GONZALEZ",
        "propietario": "YEGUADA GONZALEZ",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "8",
    "titulo": "Yeguas|7 - 11 Años",
    "orden": 10,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 34,
        "dorsal": 34,
        "nombre": "TCHAATA LADY MONA",
        "fecha_nacimiento": "2019-03-26",
        "capa": "TORDA",
        "padre": "FADI AL SHAQAB ",
        "madre": "AVALON MY LADY",
        "abuelo_materno": "MF ARYAN EL THESSA (DE)",
        "criador": "TCHAATA ARABIANS",
        "propietario": "TCHAATA ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 35,
        "dorsal": 35,
        "nombre": "ULMARIA B",
        "fecha_nacimiento": "2018-04-28",
        "capa": "TORDA",
        "padre": "QUIMONANT",
        "madre": "LAMPSANA",
        "abuelo_materno": "TIMUR",
        "criador": "BOSC DEL SISCAR",
        "propietario": "YEGUADA MI SUEÑO",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 36,
        "dorsal": 36,
        "nombre": "REINA A.A.",
        "fecha_nacimiento": "2018-04-12",
        "capa": "TORDA",
        "padre": "ADAGIO DE LUC",
        "madre": "UNION",
        "abuelo_materno": "MILORD AL SHAQAB (PL)",
        "criador": "YEGUADA ARCOS ARABIANS",
        "propietario": "YEGUADA ARCOS ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 37,
        "dorsal": 37,
        "nombre": "BERNARDINA DE LABA",
        "fecha_nacimiento": "2017-06-08",
        "capa": "TORDA",
        "padre": "EXCALIBUR E.A.",
        "madre": "ABHA RAWA",
        "abuelo_materno": "ALFABIA DAMASCUS (IT)",
        "criador": "YEGUADA LABA",
        "propietario": "YEGUADA LABA",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 38,
        "dorsal": 38,
        "nombre": "AMS ARALIA",
        "fecha_nacimiento": "2017-05-26",
        "capa": "TORDA",
        "padre": "SHAMIL AL CAPE",
        "madre": "ESMYRNA",
        "abuelo_materno": "BORNEO",
        "criador": "AMOROS ARABIAN",
        "propietario": "AMOROS ARABIAN",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "9",
    "titulo": "Yeguas|Más 11 Años",
    "orden": 11,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 39,
        "dorsal": 39,
        "nombre": "ESCITIA*",
        "fecha_nacimiento": "2011-04-04",
        "capa": "TORDA",
        "padre": "ORATE",
        "madre": "ALIC",
        "abuelo_materno": "HAIF",
        "criador": "LUIS RANGEL",
        "propietario": "LUIS RANGEL - YEGUADA LA BARBOLA",
        "notas": "Pure Spanish",
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "10",
    "titulo": "Sementales|4 - 6 Años",
    "orden": 12,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 40,
        "dorsal": 40,
        "nombre": "PM SANIS",
        "fecha_nacimiento": "2022-06-08",
        "capa": "TORDO",
        "padre": "AJ SANAD",
        "madre": "PM ANAIS",
        "abuelo_materno": "AQIR IBN TADJIRA",
        "criador": "DAVID PUJALT & TINA BAUMGARTNER",
        "propietario": "NIRRI ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 41,
        "dorsal": 41,
        "nombre": "MARCO POLO EA",
        "fecha_nacimiento": "2021-04-22",
        "capa": "TORDO",
        "padre": "SHANGHAI EA",
        "madre": "EBONY EA",
        "abuelo_materno": "GAZAL AL SHAQAB (QA)",
        "criador": "EQUUS ARABIANS",
        "propietario": "GARALOCES ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 42,
        "dorsal": 42,
        "nombre": "AD DHALI GA",
        "fecha_nacimiento": "2021-04-10",
        "capa": "TORDO",
        "padre": "ZEUS EA",
        "madre": " ABU DHABI GA",
        "abuelo_materno": "EXCALIBUR E.A.",
        "criador": "ANTONIO GONZALEZ",
        "propietario": "YEGUADA GONZALEZ",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 43,
        "dorsal": 43,
        "nombre": "MESIAS R.C.",
        "fecha_nacimiento": "2020-06-15",
        "capa": "TORDO",
        "padre": "FM THOR",
        "madre": "DG BINT SADUNGA",
        "abuelo_materno": "JAVIER EL JAMAAL (DE)",
        "criador": "ARABIANS RODRÍGUEZ CASADO",
        "propietario": "ARABIANS RODRÍGUEZ CASADO",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "11",
    "titulo": "Sementales|7 - 11 Años",
    "orden": 13,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 44,
        "dorsal": 44,
        "nombre": "L.G. RAP",
        "fecha_nacimiento": "2019-07-22",
        "capa": "NEGRO",
        "padre": "KEHSAN NADDHIM",
        "madre": "RAP-YAMILA",
        "abuelo_materno": "DIAVOLO",
        "criador": "RAP AZABACHE",
        "propietario": "G.C. ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 45,
        "dorsal": 45,
        "nombre": "ABHA CALIFA",
        "fecha_nacimiento": "2017-04-29",
        "capa": "TORDO",
        "padre": "ZEUS E.A.",
        "madre": "ABHA PALMYRIA",
        "abuelo_materno": "EL PERFECTO",
        "criador": "GANADERIAS SES PLANES",
        "propietario": "YEGUADA MI SUEÑO",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 46,
        "dorsal": 46,
        "nombre": "RA YM",
        "fecha_nacimiento": "2017-04-03",
        "capa": "CASTAÑO",
        "padre": "ISGRAM",
        "madre": "ZABALA",
        "abuelo_materno": "DRAGO 1984",
        "criador": "YEGUADA MILITAR",
        "propietario": "GANADERÍA CIRIO ARABIANS",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 47,
        "dorsal": 47,
        "nombre": "GORO*",
        "fecha_nacimiento": "2016-02-28",
        "capa": "ALAZAN",
        "padre": "GLORIOSO",
        "madre": "GORA",
        "abuelo_materno": "SUSPIRO",
        "criador": "YEGUADA EL REVUELO",
        "propietario": "VIRGEN DEL CARRASCAL",
        "notas": "Pure Spanish",
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "12",
    "titulo": "Sementales|Más 11 Años",
    "orden": 14,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 48,
        "dorsal": 48,
        "nombre": "CNOSOS E.A.",
        "fecha_nacimiento": "2012-04-29",
        "capa": "TORDO",
        "padre": "SHANGHAI E.A.",
        "madre": "CRETA EA",
        "abuelo_materno": "MADRAS KOSSACK (NL)",
        "criador": "EQUUS ARABAINS",
        "propietario": "VIRGEN DEL CARRASCAL",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      },
      {
        "id": 49,
        "dorsal": 49,
        "nombre": "LANCEADOR*",
        "fecha_nacimiento": "2011-04-10",
        "capa": "ALAZAN",
        "padre": "ECLIPSE",
        "madre": "UKOLA",
        "abuelo_materno": "OLIMPICO",
        "criador": "YEGUADA DOMECQ YBARRA",
        "propietario": "YEGUADA ARCOS ARABIANS",
        "notas": "Pure Spainsh",
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "13",
    "titulo": "Futurity|Hembra",
    "orden": 15,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 50,
        "dorsal": 50,
        "nombre": "SG UGANDA",
        "fecha_nacimiento": "2026-05-18",
        "capa": "CASTAÑA",
        "padre": "SA FALCO",
        "madre": "SG ONZA",
        "abuelo_materno": "IZAN AL CAPE",
        "criador": "YEGUADA SIERRA GORDA",
        "propietario": "YEGUADA SIERRA GORDA",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  },
  {
    "codigo": "14",
    "titulo": "Futurity|Macho",
    "orden": 16,
    "clasificacion_publicada": false,
    "caballos": [
      {
        "id": 51,
        "dorsal": 51,
        "nombre": "GHAZAL GA",
        "fecha_nacimiento": "2026-04-30",
        "capa": "CASTAÑO",
        "padre": "JYAR MEIA LUA",
        "madre": "AL-QAHIRA GA",
        "abuelo_materno": "EXCALIBUR E.A.",
        "criador": "ANTONIO GONZALEZ",
        "propietario": "YEGUADA GONZALEZ",
        "notas": null,
        "j1_t": null,
        "j1_cyc": null,
        "j1_c": null,
        "j1_e": null,
        "j1_m": null,
        "j2_t": null,
        "j2_cyc": null,
        "j2_c": null,
        "j2_e": null,
        "j2_m": null,
        "posicion": null
      }
    ]
  }
];

window.DEMO_CAMPEONATOS = [
  {
    "codigo": "potras-yearling",
    "titulo": "Potras Yearling",
    "orden": 1,
    "clases": [
      "1A",
      "1B"
    ],
    "oro_id": null,
    "plata_id": null,
    "bronce_id": null,
    "publicado": false
  },
  {
    "codigo": "potras-junior",
    "titulo": "Potras Junior",
    "orden": 2,
    "clases": [
      "3",
      "4"
    ],
    "oro_id": null,
    "plata_id": null,
    "bronce_id": null,
    "publicado": false
  },
  {
    "codigo": "potros-yearling",
    "titulo": "Potros Yearling",
    "orden": 3,
    "clases": [
      "2A",
      "2B"
    ],
    "oro_id": null,
    "plata_id": null,
    "bronce_id": null,
    "publicado": false
  },
  {
    "codigo": "potros-junior",
    "titulo": "Potros Junior",
    "orden": 4,
    "clases": [
      "5",
      "6"
    ],
    "oro_id": null,
    "plata_id": null,
    "bronce_id": null,
    "publicado": false
  },
  {
    "codigo": "yeguas",
    "titulo": "Yeguas",
    "orden": 5,
    "clases": [
      "7",
      "8",
      "9"
    ],
    "oro_id": null,
    "plata_id": null,
    "bronce_id": null,
    "publicado": false
  },
  {
    "codigo": "sementales",
    "titulo": "Sementales",
    "orden": 6,
    "clases": [
      "10",
      "11",
      "12"
    ],
    "oro_id": null,
    "plata_id": null,
    "bronce_id": null,
    "publicado": false
  }
];

window.DEMO_TROFEOS = [
  {
    "codigo": "mejor-cabeza",
    "titulo": "Mejor Cabeza",
    "orden": 1,
    "tipo": "animal",
    "ganador_caballo_id": null,
    "ganador_texto": null
  },
  {
    "codigo": "mejor-movimiento",
    "titulo": "Mejor Movimiento",
    "orden": 2,
    "tipo": "animal",
    "ganador_caballo_id": null,
    "ganador_texto": null
  },
  {
    "codigo": "prueba-libertad",
    "titulo": "Prueba de Libertad",
    "orden": 3,
    "tipo": "animal",
    "ganador_caballo_id": null,
    "ganador_texto": null
  },
  {
    "codigo": "mejor-presentador",
    "titulo": "Mejor Presentador",
    "orden": 4,
    "tipo": "texto",
    "ganador_caballo_id": null,
    "ganador_texto": null
  },
  {
    "codigo": "mejor-puntuacion",
    "titulo": "Mejor Puntuación (Best Show)",
    "orden": 5,
    "tipo": "animal",
    "ganador_caballo_id": null,
    "ganador_texto": null
  },
  {
    "codigo": "mejor-pure-spanish",
    "titulo": "Mejor Pure Spanish",
    "orden": 6,
    "tipo": "animal",
    "ganador_caballo_id": null,
    "ganador_texto": null
  }
];

window.DEMO_SORTEO = {
  id: 1,
  premio: 'Jamón',
  descripcion: 'A lo largo del concurso se realizará un sorteo entre todos los participantes.',
  ganador: null
};

window.DEMO_ANUNCIOS = [
  { id: 3, titulo: 'Horario actualizado', texto: 'La entrega de premios se adelanta media hora, a las 18:30.', creado_en: '2026-09-04T10:00:00Z' },
  { id: 2, titulo: null, texto: 'Recordamos que el aparcamiento para participantes está en la zona norte del recinto.', creado_en: '2026-09-02T09:00:00Z' },
  { id: 1, titulo: 'Bienvenidos', texto: 'Ya está abierta la inscripción de última hora en la carpa de organización.', creado_en: '2026-08-30T08:00:00Z' }
];
