-- ============================================================
-- ACTUALIZACIÓN DE INSCRIPCIONES: Zafra 2026
-- Generado a partir de ZAFRA_2026_INSCRIPCIONES_FINALES_AHC (1).xlsx
-- Ejecutar en Supabase → SQL Editor → New query → pegar → Run
-- ============================================================

-- 1) Bajas: caballos retirados del concurso
delete from caballos where trim(nombre) ilike trim('APOLO PB');
delete from caballos where trim(nombre) ilike trim('SG ONZA');

-- 2) Actualización de datos (dorsales, clase, fechas, etc.)
update caballos set clase_id = (select id from clases where codigo = '11'), dorsal = 45, nombre = 'ABHA CALIFA', fecha_nacimiento = '2017-04-29', capa = 'TORDO', padre = 'ZEUS E.A.', madre = 'ABHA PALMYRIA', criador = 'GANADERIAS SES PLANES', propietario = 'YEGUADA MI SUEÑO', notas = NULL where trim(nombre) ilike trim('ABHA CALIFA');
update caballos set clase_id = (select id from clases where codigo = '10'), dorsal = 42, nombre = 'AD DHALI GA', fecha_nacimiento = '2021-04-10', capa = 'TORDO', padre = 'ZEUS EA', madre = 'ABU DHABI GA', criador = 'ANTONIO GONZALEZ', propietario = 'YEGUADA GONZALEZ', notas = NULL where trim(nombre) ilike trim('AD DHALI GA');
update caballos set clase_id = (select id from clases where codigo = '7'), dorsal = 33, nombre = 'AL-QAHIRA GA', fecha_nacimiento = '2020-05-18', capa = 'CASTAÑA', padre = 'EXCALIBUR EA', madre = 'ABHA UDAIPUR', criador = 'ANTONIO GONZALEZ', propietario = 'YEGUADA GONZALEZ', notas = NULL where trim(nombre) ilike trim('AL-QAHIRA GA');
update caballos set clase_id = (select id from clases where codigo = '1A'), dorsal = 2, nombre = 'ALIRA DE CARO', fecha_nacimiento = '2025-06-05', capa = 'ALAZANA', padre = 'IE OTHAR', madre = 'TRIANA DE LUC', criador = 'CARO ARABIANS', propietario = 'CARO ARABIANS', notas = NULL where trim(nombre) ilike trim('ALIRA DE CARO');
update caballos set clase_id = (select id from clases where codigo = '7'), dorsal = 31, nombre = 'AMEIXENDA DE LUC', fecha_nacimiento = '2021-06-28', capa = 'TORDA', padre = 'COLISEUM E.A.', madre = 'ABHA NINUFAR', criador = 'VEL JACIR S.C.', propietario = 'ARABIANS RODRÍGUEZ CASADO', notas = NULL where trim(nombre) ilike trim('AMEIXENDA DE LUC');
update caballos set clase_id = (select id from clases where codigo = '4'), dorsal = 23, nombre = 'AMS AL ZAHRA', fecha_nacimiento = '2023-06-07', capa = 'ALAZANA', padre = 'HERODOTUS AL SHIRAA', madre = 'AMS ARALIA', criador = 'AMOROS ARABIAN', propietario = 'AMOROS ARABIAN', notas = NULL where trim(nombre) ilike trim('AMS AL ZAHRA');
update caballos set clase_id = (select id from clases where codigo = '8'), dorsal = 38, nombre = 'AMS ARALIA', fecha_nacimiento = '2017-05-26', capa = 'TORDA', padre = 'SHAMIL AL CAPE', madre = 'ESMYRNA', criador = 'AMOROS ARABIAN', propietario = 'AMOROS ARABIAN', notas = NULL where trim(nombre) ilike trim('AMS ARALIA');
update caballos set clase_id = (select id from clases where codigo = '2A'), dorsal = 8, nombre = 'AZHIR SAHIB NE', fecha_nacimiento = '2025-08-20', capa = 'ALAZAN', padre = 'AJ SANADA', madre = 'KALAIAH AL ZUBI', criador = 'GARALOCES ARABIANS', propietario = 'GARALOCES ARABIANS', notas = NULL where trim(nombre) ilike trim('AZHIR SAHIB NE');
update caballos set clase_id = (select id from clases where codigo = '1B'), dorsal = 5, nombre = 'BELA DE LABA', fecha_nacimiento = '2025-03-10', capa = 'CASTAÑA', padre = 'W.F. GAWIN', madre = 'BERNARDINA DE LABA', criador = 'YEGUADA LABA', propietario = 'YEGUADA LABA', notas = NULL where trim(nombre) ilike trim('BELA DE LABA');
update caballos set clase_id = (select id from clases where codigo = '8'), dorsal = 37, nombre = 'BERNARDINA DE LABA', fecha_nacimiento = '2017-06-08', capa = 'TORDA', padre = 'EXCALIBUR E.A.', madre = 'ABHA RAWA', criador = 'YEGUADA LABA', propietario = 'YEGUADA LABA', notas = NULL where trim(nombre) ilike trim('BERNARDINA DE LABA');
update caballos set clase_id = (select id from clases where codigo = '12'), dorsal = 48, nombre = 'CNOSOS E.A.', fecha_nacimiento = '2012-04-29', capa = 'TORDO', padre = 'SHANGHAI E.A.', madre = 'CRETA EA', criador = 'EQUUS ARABAINS', propietario = 'VIRGEN DEL CARRASCAL', notas = NULL where trim(nombre) ilike trim('CNOSOS E.A.');
update caballos set clase_id = (select id from clases where codigo = '1A'), dorsal = 1, nombre = 'DONNA H.V.', fecha_nacimiento = '2025-08-16', capa = 'TORDA', padre = 'MAGIC MAGNIFIQUE', madre = 'AFRODITA E.A.', criador = 'VACOR ARABIANS', propietario = 'VACOR ARABIANS', notas = NULL where trim(nombre) ilike trim('DONNA H.V.');
update caballos set clase_id = (select id from clases where codigo = '5'), dorsal = 25, nombre = 'EROS PB', fecha_nacimiento = '2024-06-20', capa = 'TORDO', padre = 'HARBI AL ADWAN', madre = 'ELISHARA', criador = 'DAVID PUJALT & TINA BAUMGARTNER', propietario = 'NIRRI ARABIANS', notas = NULL where trim(nombre) ilike trim('EROS PB');
update caballos set clase_id = (select id from clases where codigo = '9'), dorsal = 39, nombre = 'ESCITIA*', fecha_nacimiento = '2011-04-04', capa = 'TORDA', padre = 'ORATE', madre = 'ALIC', criador = 'LUIS RANGEL', propietario = 'LUIS RANGEL - YEGUADA LA BARBOLA', notas = 'Pure Spanish' where trim(nombre) ilike trim('ESCITIA*');
update caballos set clase_id = (select id from clases where codigo = '14'), dorsal = 51, nombre = 'GHAZAL GA', fecha_nacimiento = '2026-04-30', capa = 'CASTAÑO', padre = 'JYAR MEIA LUA', madre = 'AL-QAHIRA GA', criador = 'ANTONIO GONZALEZ', propietario = 'YEGUADA GONZALEZ', notas = NULL where trim(nombre) ilike trim('GHAZAL GA');
update caballos set clase_id = (select id from clases where codigo = '11'), dorsal = 47, nombre = 'GORO*', fecha_nacimiento = '2016-02-28', capa = 'ALAZAN', padre = 'GLORIOSO', madre = 'GORA', criador = 'YEGUADA EL REVUELO', propietario = 'VIRGEN DEL CARRASCAL', notas = 'Pure Spanish' where trim(nombre) ilike trim('GORO*');
update caballos set clase_id = (select id from clases where codigo = '6'), dorsal = 29, nombre = 'JAMAL XANDROS', fecha_nacimiento = '2023-09-26', capa = 'TORDO', padre = 'ESTORIL EA', madre = 'DAPHNE K', criador = 'JAMAL ARABIANS', propietario = 'ROCIO MORENO - MORENO ARABIANS', notas = NULL where trim(nombre) ilike trim('JAMAL XANDROS');
update caballos set clase_id = (select id from clases where codigo = '3'), dorsal = 18, nombre = 'JAMAL YAMIRA', fecha_nacimiento = '2024-03-23', capa = 'ALAZANA', padre = 'ESTORIL EA', madre = 'ABHA ODALIC', criador = 'JAMAL ARABIANS', propietario = 'JUAL ELIAS RODRIGUEZ - EL RUBIAL', notas = NULL where trim(nombre) ilike trim('JAMAL YAMIRA');
update caballos set clase_id = (select id from clases where codigo = '6'), dorsal = 30, nombre = 'JOAN', fecha_nacimiento = '2023-05-06', capa = 'TORDO', padre = 'HARIRY AL SHAQAB', madre = 'JAYWAN AL BIDAYER', criador = 'AL BAYDAA FARM', propietario = 'YEGUADA NORA', notas = NULL where trim(nombre) ilike trim('JOAN');
update caballos set clase_id = (select id from clases where codigo = '11'), dorsal = 44, nombre = 'L.G. RAP', fecha_nacimiento = '2019-07-22', capa = 'NEGRO', padre = 'KEHSAN NADDHIM', madre = 'RAP-YAMILA', criador = 'RAP AZABACHE', propietario = 'G.C. ARABIANS', notas = NULL where trim(nombre) ilike trim('L.G. RAP');
update caballos set clase_id = (select id from clases where codigo = '3'), dorsal = 15, nombre = 'L.G. UNIKA', fecha_nacimiento = '2024-07-08', capa = 'TORDA', padre = 'BV UNIK', madre = 'ANUSCHKA', criador = 'LOS GEMELOS', propietario = 'YEGUADA MI SUEÑO', notas = NULL where trim(nombre) ilike trim('L.G. UNIKA');
update caballos set clase_id = (select id from clases where codigo = '3'), dorsal = 16, nombre = 'LAA CASSANDRA', fecha_nacimiento = '2024-05-09', capa = 'TORDA', padre = 'WF GAWIN', madre = 'DAA ATHENA', criador = 'MAYRIT ARABIANS STUD', propietario = 'MAYRIT ARABIANS STUD', notas = NULL where trim(nombre) ilike trim('LAA CASANDRA');
update caballos set clase_id = (select id from clases where codigo = '5'), dorsal = 27, nombre = 'LAA CYRO', fecha_nacimiento = '2024-03-24', capa = 'TORDO', padre = 'MEDAN AL SHAQAB', madre = 'DAA BAMBOLINA', criador = 'MAYRIT ARABIANS STUD', propietario = 'MAYRIT ARABIANS STUD', notas = NULL where trim(nombre) ilike trim('LAA CYRO');
update caballos set clase_id = (select id from clases where codigo = '1B'), dorsal = 4, nombre = 'LAA DAMARIS', fecha_nacimiento = '2025-03-18', capa = 'TORDA', padre = 'LR SOLO MIO', madre = 'VENECIA DE LUC', criador = 'MAYRIT ARABIANS STUD', propietario = 'MAYRIT ARABIANS STUD', notas = NULL where trim(nombre) ilike trim('LAA DAMARIS');
update caballos set clase_id = (select id from clases where codigo = '12'), dorsal = 49, nombre = 'LANCEADOR*', fecha_nacimiento = '2011-04-10', capa = 'ALAZAN', padre = 'ECLIPSE', madre = 'UKOLA', criador = 'YEGUADA DOMECQ YBARRA', propietario = 'YEGUADA ARCOS ARABIANS', notas = 'Pure Spainsh' where trim(nombre) ilike trim('LANCEADOR*');
update caballos set clase_id = (select id from clases where codigo = '4'), dorsal = 22, nombre = 'LEENA AL SHIRAA', fecha_nacimiento = '2023-06-13', capa = 'ALAZANA', padre = 'LAUREL EL JYAR', madre = 'GHAYAT ALSBA', criador = 'AL SHIRAA ARABIANS', propietario = 'YEGUADA NORA', notas = NULL where trim(nombre) ilike trim('LEENA AL SHIRAA');
update caballos set clase_id = (select id from clases where codigo = '4'), dorsal = 24, nombre = 'LUANA AL SHIRAA', fecha_nacimiento = '2023-04-29', capa = 'ALAZANA', padre = 'HERODOTUS AL SHIRAA', madre = 'D JAMAYEL', criador = 'AL SHIRAA ARABIANS', propietario = 'IAGO y BORJA', notas = NULL where trim(nombre) ilike trim('LUANA AL SHIRAA');
update caballos set clase_id = (select id from clases where codigo = '4'), dorsal = 20, nombre = 'MAGIC DE MI SUEÑO', fecha_nacimiento = '2023-10-20', capa = 'TORDA', padre = 'ABHA CALIFA', madre = 'ULMARIA B', criador = 'YEGUADA MI SUEÑO', propietario = 'YEGUADA MI SUEÑO', notas = NULL where trim(nombre) ilike trim('MAGIC DE MI SUEÑO');
update caballos set clase_id = (select id from clases where codigo = '10'), dorsal = 41, nombre = 'MARCO POLO EA', fecha_nacimiento = '2021-04-22', capa = 'TORDO', padre = 'SHANGHAI EA', madre = 'EBONY EA', criador = 'EQUUS ARABIANS', propietario = 'GARALOCES ARABIANS', notas = NULL where trim(nombre) ilike trim('MARCO POLO EA');
update caballos set clase_id = (select id from clases where codigo = '10'), dorsal = 43, nombre = 'MESIAS R.C.', fecha_nacimiento = '2020-06-15', capa = 'TORDO', padre = 'FM THOR', madre = 'DG BINT SADUNGA', criador = 'ARABIANS RODRÍGUEZ CASADO', propietario = 'ARABIANS RODRÍGUEZ CASADO', notas = NULL where trim(nombre) ilike trim('MESIAR R.C.');
update caballos set clase_id = (select id from clases where codigo = '3'), dorsal = 17, nombre = 'MZ ANNA ALISHEEBA', fecha_nacimiento = '2024-04-27', capa = 'TORDA', padre = 'ATILA DE LUC', madre = 'SG NIEBLA', criador = 'ZEA ARABIANS', propietario = 'EVA CABRERA - GANADERÍA NOBLEZA ARABIANS', notas = NULL where trim(nombre) ilike trim('MZ ANNA ALISHEEBA');
update caballos set clase_id = (select id from clases where codigo = '2B'), dorsal = 11, nombre = 'MZ SHAMAL', fecha_nacimiento = '2025-05-07', capa = 'TORDO', padre = 'SAHM EL ARAB', madre = 'LÍBIA DE LUC', criador = 'MARTA ZEA', propietario = 'ZEA ARABIANS', notas = NULL where trim(nombre) ilike trim('MZ SHAMAL');
update caballos set clase_id = (select id from clases where codigo = '1A'), dorsal = 3, nombre = 'MZ SHAMS', fecha_nacimiento = '2025-05-22', capa = 'TORDA', padre = 'ZEUS EA', madre = 'STARBOARD BOW', criador = 'MARTA ZEA', propietario = 'ZEA ARABIANS', notas = NULL where trim(nombre) ilike trim('MZ SHAMS');
update caballos set clase_id = (select id from clases where codigo = '2B'), dorsal = 14, nombre = 'NUNO R.C.', fecha_nacimiento = '2025-03-18', capa = 'ALAZAN', padre = 'FM THOR', madre = 'MODICA DE LAGUNILLAS', criador = 'ARABIANS RODRÍGUEZ CASADO', propietario = 'ARABIANS RODRÍGUEZ CASADO', notas = NULL where trim(nombre) ilike trim('NUNO R.C.');
update caballos set clase_id = (select id from clases where codigo = '2A'), dorsal = 9, nombre = 'OBIXENTH AL ZUBI', fecha_nacimiento = '2025-06-05', capa = 'CASTAÑO', padre = 'EXAGON OS', madre = 'JULIETTAH AL ZUBI', criador = 'ZUBIALDEA ARABIANS', propietario = 'ZUBIALDEA ARABIANS', notas = NULL where trim(nombre) ilike trim('OBIXENTH AL ZUBI');
update caballos set clase_id = (select id from clases where codigo = '10'), dorsal = 40, nombre = 'PM SANIS', fecha_nacimiento = '2022-06-08', capa = 'TORDO', padre = 'AJ SANAD', madre = 'PM ANAIS', criador = 'DAVID PUJALT & TINA BAUMGARTNER', propietario = 'NIRRI ARABIANS', notas = NULL where trim(nombre) ilike trim('PM SANIS');
update caballos set clase_id = (select id from clases where codigo = '11'), dorsal = 46, nombre = 'RA YM', fecha_nacimiento = '2017-04-03', capa = 'CASTAÑO', padre = 'ISGRAM', madre = 'ZABALA', criador = 'YEGUADA MILITAR', propietario = 'GANADERÍA CIRIO ARABIANS', notas = NULL where trim(nombre) ilike trim('RA YM');
update caballos set clase_id = (select id from clases where codigo = '8'), dorsal = 36, nombre = 'REINA A.A.', fecha_nacimiento = '2018-04-12', capa = 'TORDA', padre = 'ADAGIO DE LUC', madre = 'UNION', criador = 'YEGUADA ARCOS ARABIANS', propietario = 'YEGUADA ARCOS ARABIANS', notas = NULL where trim(nombre) ilike trim('REINA A.A.');
update caballos set clase_id = (select id from clases where codigo = '5'), dorsal = 26, nombre = 'SG SAMOS', fecha_nacimiento = '2024-04-11', capa = 'ALAZAN', padre = 'AJ SANAD', madre = 'SG MYLLAS', criador = 'YEGUADA SIERRA GORDA', propietario = 'YEGUADA SIERRA GORDA', notas = NULL where trim(nombre) ilike trim('SG SAMOS');
update caballos set clase_id = (select id from clases where codigo = '1B'), dorsal = 6, nombre = 'SG TRENZA', fecha_nacimiento = '2025-03-08', capa = 'ALAZANA', padre = 'ABHA RIYADH', madre = 'YASMIN AL ZARAQ', criador = 'YEGUADA SIERRA GORDA', propietario = 'YEGUADA SIERRA GORDA', notas = NULL where trim(nombre) ilike trim('SG TRENZA');
update caballos set clase_id = (select id from clases where codigo = '1B'), dorsal = 7, nombre = 'SG TRIPOLI', fecha_nacimiento = '2025-02-26', capa = 'CASTAÑA', padre = 'ABHA RIYADH', madre = 'SG LIBIA', criador = 'YEGUADA SIERRA GORDA', propietario = 'YEGUADA SIERRA GORDA', notas = NULL where trim(nombre) ilike trim('SG TRIPOLI');
update caballos set clase_id = (select id from clases where codigo = '13'), dorsal = 50, nombre = 'SG UGANDA', fecha_nacimiento = '2026-05-18', capa = 'CASTAÑA', padre = 'SA FALCO', madre = 'SG ONZA', criador = 'YEGUADA SIERRA GORDA', propietario = 'YEGUADA SIERRA GORDA', notas = NULL where trim(nombre) ilike trim('SG UGANDA');
update caballos set clase_id = (select id from clases where codigo = '2B'), dorsal = 12, nombre = 'SHIO ISAL', fecha_nacimiento = '2025-04-20', capa = 'CASTAÑO', padre = 'SA FALCO', madre = 'DAA ISOLDA', criador = 'SHIDOME GROUP', propietario = 'LOS GEMELOS', notas = 'El propietario no coinciden en AECCA' where trim(nombre) ilike trim('SHIO ISAL');
update caballos set clase_id = (select id from clases where codigo = '3'), dorsal = 19, nombre = 'SHIO JAVA', fecha_nacimiento = '2024-03-21', capa = 'ALAZANA', padre = 'AJ SANAD', madre = 'JADA', criador = 'SHIODOME GROUP', propietario = 'LOS GEMELOS', notas = NULL where trim(nombre) ilike trim('SHIO JAVA');
update caballos set clase_id = (select id from clases where codigo = '4'), dorsal = 21, nombre = 'SHIO JULIA', fecha_nacimiento = '2023-07-17', capa = 'ALAZANA', padre = 'DOMINIC M', madre = 'JADA', criador = 'SHIODOME GROUP', propietario = 'ADRIAN RODRIGUEZ MORAN', notas = NULL where trim(nombre) ilike trim('SHIO JULIA');
update caballos set clase_id = (select id from clases where codigo = '2A'), dorsal = 10, nombre = 'SOÑADOR A.A.', fecha_nacimiento = '2025-05-15', capa = 'TORDO', padre = 'DLM KEOPS', madre = 'REINA A.A.', criador = 'YEGUADA ARCOS ARABIANS', propietario = 'YEGUADA ARCOS ARABIANS', notas = NULL where trim(nombre) ilike trim('SOÑADOR A.A.');
update caballos set clase_id = (select id from clases where codigo = '2B'), dorsal = 13, nombre = 'SUNDAR AA', fecha_nacimiento = '2025-03-21', capa = 'CASTAÑO', padre = 'AJ MARZAN', madre = 'SARAI AA', criador = 'ARIELA ARABIANS FARM', propietario = 'LA ESPARTERA', notas = NULL where trim(nombre) ilike trim('SUNDAR AA');
update caballos set clase_id = (select id from clases where codigo = '8'), dorsal = 34, nombre = 'TCHAATA LADY MONA', fecha_nacimiento = '2019-03-26', capa = 'TORDA', padre = 'FADI AL SHAQAB', madre = 'AVALON MY LADY', criador = 'TCHAATA ARABIANS', propietario = 'TCHAATA ARABIANS', notas = NULL where trim(nombre) ilike trim('TCHAATA LADY MONA');
update caballos set clase_id = (select id from clases where codigo = '8'), dorsal = 35, nombre = 'ULMARIA B', fecha_nacimiento = '2018-04-28', capa = 'TORDA', padre = 'QUIMONANT', madre = 'LAMPSANA', criador = 'BOSC DEL SISCAR', propietario = 'YEGUADA MI SUEÑO', notas = NULL where trim(nombre) ilike trim('ULMARIA B');
update caballos set clase_id = (select id from clases where codigo = '7'), dorsal = 32, nombre = 'VOLCAN DE ISORA*', fecha_nacimiento = '2021-05-31', capa = 'TORDA', padre = 'ROHF OMAN', madre = 'NYORA', criador = 'VOLCAN STUD', propietario = 'VOLCAN STUD', notas = 'Pure Spanish' where trim(nombre) ilike trim('VOLCAN DE ISORA*');
update caballos set clase_id = (select id from clases where codigo = '5'), dorsal = 28, nombre = 'VOLCAN DE TAGORO*', fecha_nacimiento = '2024-03-24', capa = 'ALAZAN', padre = 'ORGAZ ES', madre = 'NYORA', criador = 'VOLCAN STUD', propietario = 'VOLCAN STUD', notas = 'Pure Spanish' where trim(nombre) ilike trim('VOLCAN DE TAGORO*');

-- 3) Ajuste de los títulos oficiales de clase (rango de edad corregido)
update clases set titulo = 'Yeguas de 7 a 11 años' where codigo = '8';
update clases set titulo = 'Sementales de 7 a 11 años' where codigo = '11';
