-- Seed de datos: Zafra 2026 - Concurso de Pura Raza Árabe
-- Generado automáticamente a partir del Excel de inscripciones

-- Clases
insert into clases (codigo, titulo, orden) values ('1A', 'Potras 1 Año|1A', 1);
insert into clases (codigo, titulo, orden) values ('1B', 'Potras 1 Año|1B', 2);
insert into clases (codigo, titulo, orden) values ('2A', 'Potros 1 Año|2A', 3);
insert into clases (codigo, titulo, orden) values ('2B', 'Potros 1 Año|2B', 4);
insert into clases (codigo, titulo, orden) values ('3', 'Potras|2 Años', 5);
insert into clases (codigo, titulo, orden) values ('4', 'Potras|3 Años', 6);
insert into clases (codigo, titulo, orden) values ('5', 'Potros|2 Años', 7);
insert into clases (codigo, titulo, orden) values ('6', 'Potros|3 Años', 8);
insert into clases (codigo, titulo, orden) values ('7', 'Yeguas|4 - 6 Años', 9);
insert into clases (codigo, titulo, orden) values ('8', 'Yeguas|7 - 11 Años', 10);
insert into clases (codigo, titulo, orden) values ('9', 'Yeguas|Más 11 Años', 11);
insert into clases (codigo, titulo, orden) values ('10', 'Sementales|4 - 6 Años', 12);
insert into clases (codigo, titulo, orden) values ('11', 'Sementales|7 - 11 Años', 13);
insert into clases (codigo, titulo, orden) values ('12', 'Sementales|Más 11 Años', 14);
insert into clases (codigo, titulo, orden) values ('13', 'Futurity|Hembra', 15);
insert into clases (codigo, titulo, orden) values ('14', 'Futurity|Macho', 16);

-- Caballos
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '1A'), 1, 'DONNA H.V.', '2025-08-16', 'TORDA', 'MAGIC MAGNIFIQUE', 'AFRODITA E.A.', 'EXCALIBUR E.A.', 'VACOR ARABIANS', 'VACOR ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '1A'), 2, 'ALIRA DE CARO', '2025-06-05', 'ALAZANA', 'IE OTHAR', 'TRIANA DE LUC', 'COLISEUM E.A.', 'CARO ARABIANS', 'CARO ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '1A'), 3, 'MZ SHAMS', '2025-05-22', 'TORDA', 'ZEUS EA', 'STARBOARD BOW', 'STIVAL (US)', 'MARTA ZEA', 'ZEA ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '1B'), 4, 'LAA DAMARIS', '2025-03-18', 'TORDA', 'LR SOLO MIO', 'VENECIA DE LUC', 'SHANGHAI E.A.', 'MAYRIT ARABIANS STUD', 'MAYRIT ARABIANS STUD', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '1B'), 5, 'BELA DE LABA', '2025-03-10', 'CASTAÑA', 'W.F. GAWIN', 'BERNARDINA DE LABA', 'EXCALIBUR E.A.', 'YEGUADA LABA', 'YEGUADA LABA', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '1B'), 6, 'SG TRENZA', '2025-03-08', 'ALAZANA', 'ABHA RIYADH', 'YASMIN AL ZARAQ', 'L.C. HAREM', 'YEGUADA SIERRA GORDA', 'YEGUADA SIERRA GORDA', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '1B'), 7, 'SG TRIPOLI', '2025-02-26', 'CASTAÑA', 'ABHA RIYADH', 'SG LIBIA', 'COLISEUM E.A.', 'YEGUADA SIERRA GORDA', 'YEGUADA SIERRA GORDA', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '2A'), 8, 'AZHIR SAHIB NE', '2025-08-20', 'ALAZAN', 'AJ SANADA', 'KALAIAH AL ZUBI', 'EB JAMAL', 'GARALOCES ARABIANS', 'GARALOCES ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '2A'), 9, 'OBIXENTH AL ZUBI', '2025-06-05', 'CASTAÑO', 'EXAGON OS', 'JULIETTAH AL ZUBI', 'KANZ ALBIDAYER', 'ZUBIALDEA ARABIANS', 'ZUBIALDEA ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '2A'), 10, 'SOÑADOR A.A.', '2025-05-15', 'TORDO', 'DLM KEOPS', 'REINA A.A.', 'ADAGIO DE LUC', 'YEGUADA ARCOS ARABIANS', 'YEGUADA ARCOS ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '2B'), 11, 'MZ SHAMAL', '2025-05-07', 'TORDO', 'SAHM EL ARAB', 'LÍBIA DE LUC', 'FLAVIO DE LUC', 'MARTA ZEA', 'ZEA ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '2B'), 12, 'SHIO ISAL', '2025-04-20', 'CASTAÑO', 'SA FALCO', 'DAA ISOLDA', 'QR MARC', 'SHIDOME GROUP', 'LOS GEMELOS', 'El propietario no coinciden en AECCA');
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '2B'), 13, 'SUNDAR AA', '2025-03-21', 'CASTAÑO', 'AJ MARZAN', 'SARAI AA', 'JYAR MEIA LUA', 'ARIELA ARABIANS FARM', 'LA ESPARTERA', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '2B'), 14, 'NUNO R.C.', '2025-03-18', 'ALAZAN', 'FM THOR', 'MODICA DE LAGUNILLAS', 'ABHA VOLTAIRE', 'ARABIANS RODRÍGUEZ CASADO', 'ARABIANS RODRÍGUEZ CASADO', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '3'), 15, 'L.G. UNIKA', '2024-07-08', 'TORDA', 'BV UNIK', 'ANUSCHKA', 'CLASSIC KARIM', 'LOS GEMELOS', 'YEGUADA MI SUEÑO', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '3'), 16, 'LAA CASSANDRA', '2024-05-09', 'TORDA', 'WF GAWIN', 'DAA ATHENA', 'MAKISA ADAGGIO', 'MAYRIT ARABIANS STUD', 'MAYRIT ARABIANS STUD', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '3'), 17, 'MZ ANNA ALISHEEBA', '2024-04-27', 'TORDA', 'ATILA DE LUC', 'SG NIEBLA', 'ABHA ORIX', 'ZEA ARABIANS', 'EVA CABRERA - GANADERÍA NOBLEZA ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '3'), 18, 'JAMAL YAMIRA', '2024-03-23', 'ALAZANA', 'ESTORIL EA', 'ABHA ODALIC', 'KHIDAR', 'JAMAL ARABIANS', 'JUAL ELIAS RODRIGUEZ - EL RUBIAL', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '3'), 19, 'SHIO JAVA', '2024-03-21', 'ALAZANA', 'AJ SANAD', 'JADA', 'QR MARC', 'SHIODOME GROUP', 'LOS GEMELOS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '4'), 20, 'MAGIC DE MI SUEÑO', '2023-10-20', 'TORDA', 'ABHA CALIFA', 'ULMARIA B', 'QUIMONANT', 'YEGUADA MI SUEÑO', 'YEGUADA MI SUEÑO', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '4'), 21, 'SHIO JULIA', '2023-07-17', 'ALAZANA', 'DOMINIC M', 'JADA', 'QR MARC', 'SHIODOME GROUP', 'ADRIAN RODRIGUEZ MORAN', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '4'), 22, 'LEENA AL SHIRAA', '2023-06-13', 'ALAZANA', 'LAUREL EL JYAR', 'GHAYAT ALSBA', 'SHAEL DREAM DESERT', 'AL SHIRAA ARABIANS', 'YEGUADA NORA', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '4'), 23, 'AMS AL ZAHRA', '2023-06-07', 'ALAZANA', 'HERODOTUS AL SHIRAA', 'AMS ARALIA', 'SHAMIL AL CAPÉ', 'AMOROS ARABIAN', 'AMOROS ARABIAN', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '4'), 24, 'LUANA AL SHIRAA', '2023-04-29', 'ALAZANA', 'HERODOTUS AL SHIRAA', 'D JAMAYEL', 'FA EL RASHEEM', 'AL SHIRAA ARABIANS', 'IAGO y BORJA', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '5'), 25, 'EROS PB', '2024-06-20', 'TORDO', 'HARBI AL ADWAN', 'ELISHARA', 'KHIDAR', 'DAVID PUJALT & TINA BAUMGARTNER', 'NIRRI ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '5'), 26, 'SG SAMOS', '2024-04-11', 'ALAZAN', 'AJ SANAD', 'SG MYLLAS', 'FLAVIO DE LUC', 'YEGUADA SIERRA GORDA', 'YEGUADA SIERRA GORDA', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '5'), 27, 'LAA CYRO', '2024-03-24', 'TORDO', 'MEDAN AL SHAQAB', 'DAA BAMBOLINA', 'AJMAN MONISCIONE', 'MAYRIT ARABIANS STUD', 'MAYRIT ARABIANS STUD', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '5'), 28, 'VOLCAN DE TAGORO*', '2024-03-24', 'ALAZAN', 'ORGAZ ES', 'NYORA', 'IZABAL', 'VOLCAN STUD', 'VOLCAN STUD', 'Pure Spanish');
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '6'), 29, 'JAMAL XANDROS', '2023-09-26', 'TORDO', 'ESTORIL EA', 'DAPHNE K', 'WH JUSTICE', 'JAMAL ARABIANS', 'ROCIO MORENO - MORENO ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '6'), 30, 'JOAN', '2023-05-06', 'TORDO', 'HARIRY AL SHAQAB', 'JAYWAN AL BIDAYER', 'D KHATTAF', 'AL BAYDAA FARM', 'YEGUADA NORA', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '7'), 31, 'AMEIXENDA DE LUC', '2021-06-28', 'TORDA', 'COLISEUM E.A.', 'ABHA NINUFAR', 'MARWAN AL SHAQAB (QA)', 'VEL JACIR S.C.', 'ARABIANS RODRÍGUEZ CASADO', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '7'), 32, 'VOLCAN DE ISORA*', '2021-05-31', 'TORDA', 'ROHF OMAN', 'NYORA', 'IZABAL', 'VOLCAN STUD', 'VOLCAN STUD', 'Pure Spanish');
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '7'), 33, 'AL-QAHIRA GA', '2020-05-18', 'CASTAÑA', 'EXCALIBUR EA', 'ABHA UDAIPUR', 'ABHA PESHAWAR', 'ANTONIO GONZALEZ', 'YEGUADA GONZALEZ', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '8'), 34, 'TCHAATA LADY MONA', '2019-03-26', 'TORDA', 'FADI AL SHAQAB', 'AVALON MY LADY', 'MF ARYAN EL THESSA (DE)', 'TCHAATA ARABIANS', 'TCHAATA ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '8'), 35, 'ULMARIA B', '2018-04-28', 'TORDA', 'QUIMONANT', 'LAMPSANA', 'TIMUR', 'BOSC DEL SISCAR', 'YEGUADA MI SUEÑO', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '8'), 36, 'REINA A.A.', '2018-04-12', 'TORDA', 'ADAGIO DE LUC', 'UNION', 'MILORD AL SHAQAB (PL)', 'YEGUADA ARCOS ARABIANS', 'YEGUADA ARCOS ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '8'), 37, 'BERNARDINA DE LABA', '2017-06-08', 'TORDA', 'EXCALIBUR E.A.', 'ABHA RAWA', 'ALFABIA DAMASCUS (IT)', 'YEGUADA LABA', 'YEGUADA LABA', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '8'), 38, 'AMS ARALIA', '2017-05-26', 'TORDA', 'SHAMIL AL CAPE', 'ESMYRNA', 'BORNEO', 'AMOROS ARABIAN', 'AMOROS ARABIAN', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '9'), 39, 'ESCITIA*', '2011-04-04', 'TORDA', 'ORATE', 'ALIC', 'HAIF', 'LUIS RANGEL', 'LUIS RANGEL - YEGUADA LA BARBOLA', 'Pure Spanish');
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '10'), 40, 'PM SANIS', '2022-06-08', 'TORDO', 'AJ SANAD', 'PM ANAIS', 'AQIR IBN TADJIRA', 'DAVID PUJALT & TINA BAUMGARTNER', 'NIRRI ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '10'), 41, 'MARCO POLO EA', '2021-04-22', 'TORDO', 'SHANGHAI EA', 'EBONY EA', 'GAZAL AL SHAQAB (QA)', 'EQUUS ARABIANS', 'GARALOCES ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '10'), 42, 'AD DHALI GA', '2021-04-10', 'TORDO', 'ZEUS EA', 'ABU DHABI GA', 'EXCALIBUR E.A.', 'ANTONIO GONZALEZ', 'YEGUADA GONZALEZ', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '10'), 43, 'MESIAS R.C.', '2020-06-15', 'TORDO', 'FM THOR', 'DG BINT SADUNGA', 'JAVIER EL JAMAAL (DE)', 'ARABIANS RODRÍGUEZ CASADO', 'ARABIANS RODRÍGUEZ CASADO', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '11'), 44, 'L.G. RAP', '2019-07-22', 'NEGRO', 'KEHSAN NADDHIM', 'RAP-YAMILA', 'DIAVOLO', 'RAP AZABACHE', 'G.C. ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '11'), 45, 'ABHA CALIFA', '2017-04-29', 'TORDO', 'ZEUS E.A.', 'ABHA PALMYRIA', 'EL PERFECTO', 'GANADERIAS SES PLANES', 'YEGUADA MI SUEÑO', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '11'), 46, 'RA YM', '2017-04-03', 'CASTAÑO', 'ISGRAM', 'ZABALA', 'DRAGO 1984', 'YEGUADA MILITAR', 'GANADERÍA CIRIO ARABIANS', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '11'), 47, 'GORO*', '2016-02-28', 'ALAZAN', 'GLORIOSO', 'GORA', 'SUSPIRO', 'YEGUADA EL REVUELO', 'VIRGEN DEL CARRASCAL', 'Pure Spanish');
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '12'), 48, 'CNOSOS E.A.', '2012-04-29', 'TORDO', 'SHANGHAI E.A.', 'CRETA EA', 'MADRAS KOSSACK (NL)', 'EQUUS ARABAINS', 'VIRGEN DEL CARRASCAL', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '12'), 49, 'LANCEADOR*', '2011-04-10', 'ALAZAN', 'ECLIPSE', 'UKOLA', 'OLIMPICO', 'YEGUADA DOMECQ YBARRA', 'YEGUADA ARCOS ARABIANS', 'Pure Spainsh');
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '13'), 50, 'SG UGANDA', '2026-05-18', 'CASTAÑA', 'SA FALCO', 'SG ONZA', 'IZAN AL CAPE', 'YEGUADA SIERRA GORDA', 'YEGUADA SIERRA GORDA', NULL);
insert into caballos (clase_id, dorsal, nombre, fecha_nacimiento, capa, padre, madre, abuelo_materno, criador, propietario, notas) values ((select id from clases where codigo = '14'), 51, 'GHAZAL GA', '2026-04-30', 'CASTAÑO', 'JYAR MEIA LUA', 'AL-QAHIRA GA', 'EXCALIBUR E.A.', 'ANTONIO GONZALEZ', 'YEGUADA GONZALEZ', NULL);

-- Campeonatos
insert into campeonatos (codigo, titulo, orden, clases) values ('potras-yearling', 'Potras Yearling', 1, '["1A", "1B"]'::jsonb);
insert into campeonatos (codigo, titulo, orden, clases) values ('potras-junior', 'Potras Junior', 2, '["3", "4"]'::jsonb);
insert into campeonatos (codigo, titulo, orden, clases) values ('potros-yearling', 'Potros Yearling', 3, '["2A", "2B"]'::jsonb);
insert into campeonatos (codigo, titulo, orden, clases) values ('potros-junior', 'Potros Junior', 4, '["5", "6"]'::jsonb);
insert into campeonatos (codigo, titulo, orden, clases) values ('yeguas', 'Yeguas', 5, '["7", "8", "9"]'::jsonb);
insert into campeonatos (codigo, titulo, orden, clases) values ('sementales', 'Sementales', 6, '["10", "11", "12"]'::jsonb);

-- Trofeos
insert into trofeos (codigo, titulo, orden, tipo) values ('mejor-cabeza', 'Mejor Cabeza', 1, 'animal');
insert into trofeos (codigo, titulo, orden, tipo) values ('mejor-movimiento', 'Mejor Movimiento', 2, 'animal');
insert into trofeos (codigo, titulo, orden, tipo) values ('prueba-libertad', 'Prueba de Libertad', 3, 'animal');
insert into trofeos (codigo, titulo, orden, tipo) values ('mejor-presentador', 'Mejor Presentador', 4, 'texto');
insert into trofeos (codigo, titulo, orden, tipo) values ('mejor-puntuacion', 'Mejor Puntuación (Best Show)', 5, 'animal');
insert into trofeos (codigo, titulo, orden, tipo) values ('mejor-pure-spanish', 'Mejor Pure Spanish', 6, 'animal');

-- Sorteo
insert into sorteo (id) values (1) on conflict (id) do nothing;
